"""
Constants used in other files
"""

# URL of the default Chess.com avatar
default_avatar_url = "https://www.chess.com/bundles/web/images/noavatar_l.84a92436.gif"

# Some strings for data formatting
html_start = "<html><head/><body>"
html_end = "</body></html>"
html_title = '<span style=" font-size:10pt; font-weight:600;">%s</span>'

# Big text blocks for detail window
detail_game = '<html><head/><body><p align="center"><br/></p><p align="center"><span style=" font-size:14pt; font-weight:600; color:#ffcc00;">GAME</span></p><p align="center">Time control: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">End time: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Is it rated? <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">UUID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Time class: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Rules: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center"><br/></p><p align="center"><span style=" font-size:14pt; font-weight:600; color:#ffcc00;">PLAYERS</span><br/></p><p align="center"><span style=" font-size:11pt; font-weight:600;">White</span></p><p align="center">Username: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Rating: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Result: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">ID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">UUID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Accuracy: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center"><br/></p><p align="center"><span style=" font-size:11pt; font-weight:600;">Black</span></p><p align="center">Username: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Rating: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Result: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">ID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">UUID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Accuracy: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center"><br/></p></body></html>'
detail_player = '<html><head/><body><p align="center"><br/></p><p align="center"><span style=" font-size:14pt; font-weight:600; color:#ffcc00;">PLAYER</span></p><p align="center">Player ID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Api ID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Username: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Score: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Rank: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Country: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Status: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Avatar URL: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Flair: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Name: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Wins: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Losses: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Draws: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Winrate: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center"><br/></p><p align="center"><br/></p></body></html>'
