"""
Constants used in other files
"""

# URL of the default Chess.com avatar
default_avatar_url = "https://www.chess.com/bundles/web/images/noavatar_l.84a92436.gif"

# Some strings for data formatting
html_start = "<html><head/><body>"
html_end = "</body></html>"
html_title = '<span style=" font-size:10pt; font-weight:600;">%s</span>'

# Big text blocks for detail window
detail_game = '<html><head/><body><p align="center"><br/></p><p align="center"><span style=" font-size:14pt; font-weight:600; color:#ffcc00;">PARTIDA</span></p><p align="center">Control de tiempo: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Acabada en: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Es puntuada? <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">UUID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Modo de juego: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Reglas: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center"><br/></p><p align="center"><span style=" font-size:14pt; font-weight:600; color:#ffcc00;">JUGADORES</span><br/></p><p align="center"><span style=" font-size:11pt; font-weight:600;">Blancas</span></p><p align="center">Usuario: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Puntuacion: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Resultado: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">ID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">UUID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Precisión: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center"><br/></p><p align="center"><span style=" font-size:11pt; font-weight:600;">Black</span></p><p align="center">Usuario: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Puntuacion: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Resultado: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">ID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">UUID: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Precisión: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center"><br/></p></body></html>'
detail_player = '<html><head/><body><p align="center"><br/></p><p align="center"><span style=" font-size:14pt; font-weight:600; color:#ffcc00;">JUGADOR</span></p><p align="center">ID de jugador: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">ID de api: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Usuario: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Puntuación: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Rango: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Ciudad: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Estado: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">URL del avatar: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Icono: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Nombre: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Victorias: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Derrotas: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">Empates: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center">% de victorias: <span style=" font-style:italic; color:#ffcc00;">%s</span></p><p align="center"><br/></p><p align="center"><br/></p></body></html>'
